// export const pie_data_all = [
//     {
//         title: "Pie 1 ",
//         picture: require("./assets/rgrim_pie_slider2/pie1.png"),
//         bg_color: "#8e5d7b",
//         key: 1,
//     },
//     {
//         title: "Pie 2 ",
//         picture: require("./assets/rgrim_pie_slider2/pie2.png"),
//         bg_color: "#900d01",
//         key: 2,
//     },
//     {
//         title: "Pie 3 ",
//         picture: require("./assets/rgrim_pie_slider2/pie3.png"),
//         bg_color: "#ab0016",
//         key: 3,
//     },
//     {
//         title: "Pie 4 ",
//         picture: require("./assets/rgrim_pie_slider2/pie4.png"),
//         bg_color: "#d09b5e",
//         key: 4,
//     },
//     {
//         title: "Pie 5 ",
//         picture: require("./assets/rgrim_pie_slider2/pie5.png"),
//         bg_color: "#d86d02",
//         key: 5,
//     },
//     {
//         title: "Pie 6 ",
//         picture: require("./assets/rgrim_pie_slider2/pie6.png"),
//         bg_color: "#e11c10",
//         key: 6,
//     },
//     {
//         title: "Pie 7 ",
//         picture: require("./assets/rgrim_pie_slider2/pie7.png"),
//         bg_color: "#df8563",
//         key: 7,
//     },
//     {
//         title: "Pie 8 ",
//         picture: require("./assets/rgrim_pie_slider2/pie8.png"),
//         bg_color: "#b45503",
//         key: 8,
//     },
// ];

export const pie_data = [
    {
        title: "BlueBerry Pie ",
        about_color: "#872961",
        about: "A classic dessert bursting with plump, juicy blueberries in a flaky, golden crust, creating a harmonious blend of sweet and tart flavors.",
        picture: require("../assets/rgrim_pie_slider2/pie1.png"),
        bg_color: "#8e5d7b",
        key: 1,
    },
    {
        title: "Strawberry Pie ",
        about_color: "#77261f",
        about: "Indulge in the luscious sweetness of ripe strawberries embraced by a buttery, tender crust, capturing the essence of summer in every bite.",
        picture: require("../assets/rgrim_pie_slider2/pie2.png"),
        bg_color: "#900d01",
        key: 2,
    },
    {
        title: "Bread Pie",
        about_color: "#cc791a",
        about: "A delightful twist on tradition, our Bread Pie features a comforting medley of flavors and textures, with a warm, spiced filling encased in a uniquely satisfying crust.",
        picture: require("../assets/rgrim_pie_slider2/pie4.png"),
        bg_color: "#d09b5e",
        key: 4,
    },
    {
        title: "Cherry Pie",
        about_color: "#77261f",
        about: "Juicy cherries embraced by a golden crust, a timeless dessert that's pure delight in every slice.",
        picture: require("../assets/rgrim_pie_slider2/pie3.png"),
        bg_color: "#ab0016",
        key: 3,
    },
    {
        title: "Caramel Pie",
        about_color: "#af5a0a",
        about: "Savor the rich allure of velvety caramel harmonizing with a delicate pastry shell, creating a dessert that's a symphony of silky sweetness.",
        picture: require("../assets/rgrim_pie_slider2/pie5.png"),
        bg_color: "#d86d02",
        key: 5,
    },
    {
        title: "Fruit Pie",
        about_color: "#b20e05",
        about: "Experience a burst of vibrant flavors in every slice as an array of succulent fruits unite in a single, delectable pie, offering a rainbow of taste in each bite.",
        picture: require("../assets/rgrim_pie_slider2/pie6.png"),
        bg_color: "#e11c10",
        key: 6,
    },
    {
        title: "Blue Pie ",
        about_color: "#d34613",
        about: " Elevate your senses with our enchanting Blue Pie, where a medley of blue fruits meld in a delightful symphony, wrapped in a tender, golden crust.",
        picture: require("../assets/rgrim_pie_slider2/pie7.png"),
        bg_color: "#df8563",
        key: 7,
    },
    {
        title: "Cashew Pie ",
        about_color: "#964b0f",
        about: " Discover a nut lover's dream in every forkful – a luxuriously nutty creation where creamy cashews meet a flaky, melt-in-your-mouth pastry.",
        picture: require("../assets/rgrim_pie_slider2/pie8.png"),
        bg_color: "#b45503",
        key: 8,
    },
];

